version : "3.8"
services:
  mysql:
    container_name: review2
    image : mysql:latest
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_data:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD : password
      MYSQL_DATABASE : review_sql
      MYSQL_PASSWORD : password
    ports:
      - "3301:3306"

  redis:
    container_name: onus-redis
    image : redis:latest
    ports:
      - "6379:6379"
    restart : unless-stopped